modLoader="javafml"
loaderVersion="[47,)"
license="Custom license"

[[mods]]
modId="eventjar"
version="2.0.0"
displayName="Event.jar"
displayURL="https://www.donationalerts.com/r/dj_univxrsel"
credits="<meatboy> i am the god"
authors="Lixis9"
description="you are godless"

[[mixins]]
config="mixins.eventjar.json"

[[mixins]]
config="outofbound.mixins.json"

[[dependencies.eventjar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"
